Removes pariah gun code and updates tg gun code
DaedalusDock/daedalusdock pull request #245
Opened 2023-03-02 12:38 UTC by DTraitor

## About The Pull Request
Pariah Station had it's own gun code. Highly modified tg to be exact. I removed it and updated the gun code to the latest tg. It fixed some bugs and also made the code a lot more maintainable.

## Why It's Good For The Game
`LessBadCode == Good`
Also fixes a bug that didn't add action button that switched fire modes.

## Changelog

:cl:
refactor: Replaced Pariah gun code with tg gun code.
/:cl:

2023-03-02 19:21 UTC, Kapu1178 requested changes

2023-03-02 19:21 UTC, Kapu1178 commented on code/datums/elements/weapon_description.dm
> +	id_arg_index = 2
weapon descriptions were explicitly removed

2023-03-09 17:53 UTC, Kapu1178 commented
will tm: 👍

2023-03-10 13:47 UTC, gonenoculer5 requested changes
I might've missed a few things here but anything relating to a mention of NT in any fashion needs to be reverted back to what it was. A few other questions though would be why the detectives revolver was renamed to C38 if you know, probably just a TG-ism if I had to guess. I also dont personally really like the use of so many balloon alerts, as I believe to_chat() is more preferable when balloon alerts look so terrible. This obviously comes down to more of being Kapu's choice, but I thought I'd throw my hat in the ring.

2023-03-10 13:47 UTC, gonenoculer5 commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "First generation lasergun, developed by Nanotrasen. Suffers from ammo issues but its unique ability to recharge its ammo without the need of a magazine helps compensate. You really hope some
Ditto.

2023-03-12 11:16 UTC, gonenoculer5 reviewed
Looks good now. Up to Kapu if he wants to move towards using balloon alerts, or keep using to_chat() as we did originally. Personally I prefer to_chat() over balloon's, but its his and frans call.

2023-03-21 02:34 UTC, Kapu1178 commented
YOLO MERGEEEEE

2023-03-21 02:34 UTC, merged