Allow lone op disk nag to be disabled
DaedalusDock/daedalusdock pull request #349
Opened 2023-06-01 03:37 UTC by francinum

Will reenable on config reload

## About The Pull Request

Allows the disk security system to be safely disabled and reenabled via config.

## Why It's Good For The Game

Lowpop nag, and the way this works is so cheap it doesn't really matter.

## Changelog

:cl:
config: Lone Op disk security nagging can now be configured.
/:cl:

2023-06-02 01:32 UTC, Kapu1178 requested changes

2023-06-02 01:32 UTC, Kapu1178 commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
>  	var/turf/new_turf = get_turf(src)
dont use componentinitialize its dying

2023-06-03 06:55 UTC, francinum commented on code/modules/antagonists/nukeop/equipment/nuclearbomb.dm
>  	var/turf/new_turf = get_turf(src)
You misread the code.

2023-06-03 18:43 UTC, Kapu1178 approved these changes

2023-06-14 01:08 UTC, merged