Adds feral hogs, maint slugs, and replaces the HOS and janitor's pets
DaedalusDock/daedalusdock pull request #386
Opened 2023-06-22 03:57 UTC by Spyroshark

## About The Pull Request

Adds Maintenance Slugs and Feral Hogs to the game. Slugs are passive and can be found in maint on occasion, and leave a trail of slippery slime as they crawl around. Their "udders" (aka "slime glands" or "sludders" if you're so inclined) can be "milked" to collect their slime, which is slippery, cleans tiles, and works as a surgical chem.

Feral Hogs are a neutral mob that will turn hostile when anything gets too close. They currently only spawn during the Animal Infestation event, and should be a very rare sight. I will consider adding more ways to find hogs later on. (hog antag 2024). also they're insanely strong so don't spawn 30-40 of them please

This PR also removes the HOS' pet spider and the janitor's pet(?) lizard in favor of two new pets, Lieutenant Hoggison and Glubby. Hoggison is a security pig that gets his own pen by the security lockers and is much more passive then normal hogs. Glubby is a unique slug that the janitor can use to help clean floors, and also has a unique udder interaction.

## Why It's Good For The Game

Nobody even remembers the janitor has a pet, and the hos' spider is a BAT. I think these are more fun replacements. Slugs in maint are fun and uncommon enough to not get too annoying, and the rare occasional hog attack is incredibly funny to me.

## Changelog

:cl:
add: Maint Slugs! They leave behind a slippery trail and can be "milked" if so desired. The janitor starts with a unique one.
add: Feral Hogs! Technically a neutral animal, they become aggressive if you get too close. Security has a private hog.
del: Sgt. Araneus and Wags-His-Tail have been sent off to kindly old man's space-farm, where they will happily live out the rest of their natural lives.
/:cl:

2023-06-22 04:16 UTC, Kapu1178 requested changes
initial

2023-06-22 04:16 UTC, Kapu1178 commented on code/modules/mob/living/simple_animal/hostile/retaliate/hog.dm
> +	if(name == "feral hog") //don't rename renamed hogs
```suggestion
	if(name == initial(name)) //don't rename renamed hogs
```

2023-06-22 04:51 UTC, Kapu1178 requested changes

2023-06-22 04:51 UTC, Kapu1178 commented on code/modules/mob/living/simple_animal/hostile/retaliate/hog.dm
> +	flick_overlay_view(alert_overlay, src, 1.5 SECONDS)
Use vis_contents for this.

```
var/obj/effect/overlay/vis/overlay = new()
overlay .icon = 'icons/mob/animal.dmi'
overlay .icon_state = 'icons/mob/animal.dmi
vis_contents += overlay
QDEL_IN(overlay, 1.5 SECONDS)
```

2023-06-22 05:51 UTC, Spyroshark commented on code/modules/mob/living/simple_animal/hostile/retaliate/hog.dm
> +	flick_overlay_view(alert_overlay, src, 1.5 SECONDS)
done

2023-06-25 23:56 UTC, Cenrus commented
Add the ridable element to the hog, cows use it too

2023-06-26 18:37 UTC, Spyroshark commented
> Add the ridable element to the hog, cows use it too

i was told specifically to not add ridable hogs. however perhaps it is better to die standing then to live kneeling

2023-07-02 22:37 UTC, FunnyLegJiggle commented on code/modules/mob/living/simple_animal/hostile/retaliate/hog.dm
> +	if(prob(15))
does not check for the alive state of the mob, allowing HOG grunting from the afterlife if the body is moved

2023-09-02 15:35 UTC, Spyroshark commented
oops

2023-09-02 15:35 UTC, closed without merging