Centralized Media Management
DaedalusDock/daedalusdock pull request #430
Opened 2023-07-11 02:04 UTC by francinum

## About The Pull Request

Refactors configurable media track management into a centralized, shared system.

Also kills the disco jukebox, that thing's a dumpster fire.

## Why It's Good For The Game

Centralized management allows for tracks to be parsed exactly once, instead of repeatedly for the various purposes, as well as allowing sounds to be cleanly shared between pools, such as allowing various title tracks to be played in the IC jukeboxes.

## Changelog

:cl:
config: Credits music, Lobby tracks, and Jukebox media organization has changed massively. Check the repo for more information.
del: Disco Inferno has been made far less disco.
/:cl:

2023-07-11 11:30 UTC, gonenoculer5 commented
I can't believe they killed disco inferno

2023-08-01 00:56 UTC, Kapu1178 requested changes
rustg

2023-08-01 00:56 UTC, Kapu1178 commented on code/controllers/subsystem/ticker.dm
> +	if(fexists("data/last_round_lobby_music.txt"))
```suggestion
	if(rustg_file_exists("data/last_round_lobby_music.txt"))
```

2023-08-01 00:56 UTC, Kapu1178 commented on code/controllers/subsystem/ticker.dm
> +		old_login_music_t = file2text("data/last_round_lobby_music.txt")
```suggestion
		old_login_music_t = rustg_file_read("data/last_round_lobby_music.txt")
```

2023-08-01 00:56 UTC, Kapu1178 commented on code/controllers/subsystem/media.dm
> +		var/list/json_data = json_decode(file2text("[basedir][json_record]"))
```suggestion
		var/list/json_data = json_decode(rustg_file_read("[basedir][json_record]"))
```

2023-08-01 00:56 UTC, Kapu1178 commented on code/controllers/subsystem/media.dm
> +					if(!fexists(jd_full_filepath))
```suggestion
					if(!rustg_file_exists(jd_full_filepath))
```

2023-08-05 02:41 UTC, merged