Data Terminals are now buildable
DaedalusDock/daedalusdock pull request #560
Opened 2023-09-06 23:04 UTC by francinum

Allows construction and destruction of data terminals, and fixes phone terminal link messages.

## Changelog

:cl:
add: Data Terminals are buildable, you can get them from the Engineering Fabricator.
fix: phone connection feedback messages no longer error on trying to connect to a terminal it's already connected to.
/:cl:

2023-09-06 23:07 UTC, francinum commented on code/modules/power/data_terminal.dm
> +		"you start screwing [src] into \the [T]",
```suggestion
		"You start screwing [src] into \the [T]",
```

2023-09-06 23:07 UTC, francinum commented on code/modules/power/data_terminal.dm
> +	user.visible_message("[user] installed \the [src] to \the [T]", "You installed \the [src] to \the [T]")
```suggestion
	user.visible_message("[user] installed \the [src] on \the [T]", "You installed \the [src] on \the [T]")
```

2023-09-06 23:07 UTC, francinum commented on code/modules/power/data_terminal.dm
> +		"you start unscrewing [src] from \the [src.loc]",
```suggestion
		"You start unscrewing [src] from \the [src.loc]",
```

2023-09-12 01:17 UTC, Kapu1178 requested changes

2023-09-12 01:17 UTC, Kapu1178 commented on code/modules/power/data_terminal.dm
> +/obj/machinery/power/data_terminal/screwdriver_act(mob/living/user, obj/item/tool)
New lines please

2023-09-12 01:17 UTC, Kapu1178 commented on code/modules/power/data_terminal.dm
> +/obj/item/data_terminal_construct/screwdriver_act(mob/living/user, obj/item/tool)
new lines please

2023-09-16 02:11 UTC, merged