Porting most things from TGstation (Actions refactoring, statpanel reworking, alt examine reworking, text_ref, defines for Byond 515)
DaedalusDock/daedalusdock pull request #82
Opened 2022-11-18 23:40 UTC by DeadLineSS13

## About The Pull Request
This PR porting tgstation/tgstation#67083, tgstation/tgstation#69825, tgstation/tgstation#66971 and part porting tgstation/tgstation#70729, tgstation/tgstation#71161

## Why It's Good For The Game
Theses things cool and most refactoring.

## Changelog

:cl: Melbert, LemonInTheDark
add: The Mjolnir wizard loadout no longer scams you. It now also grants 1 level of Tesla Blast!
fix: Spells show up in the stat panel again
fix: Fixes runtime errors that can occur if a wizard spellbook randomizes into unpurchasable spells.
fix: Genetics powers now have their own background, which apparently they have always meant to have.
fix: Fixes some cases where chaplains are unable to cast their own spells.
fix: Fixes some granters being infinite when they should've been limited (Maint loot books).
fix: Wizard's roundend report is now more accurate in what spells they purchased.
qol: Some more spells and actions now use balloon alerts.
qol: Many actions will now more accurately have their icon redded out if you can't use them at the moment.
qol: Genetics mindread is now a pointed ability.
qol: The mimery book now grants you a vow of silence action, like the guide to advanced mimery.
qol: Xenomorph's corrosive acid ability is now a click-to-work action, so you click on what you want to acid.
qol: Also, xenomorph larva now use a radial when choosing an evolution type.
qol: Summon Item now takes a few seconds to remove the mark from an item, so you no longer accidentally remove it.
balance: The mindswap book now gives a slight message warning it's changed on read.
balance: Sacred Flame now lets people around them know they're actually being made super flammable.
balance: Olfaction can't be cast if you have no nose (you're headless).
balance: Being Emotemute now prevents you from invoking spells which require emotes (mime spells).
balance: All wizard spells except Mindswap can't be cast if the wizard is just a brain. Most spells didn't work, anyways.
balance: PAIs and carded AIs can no longer cast spells. Most spells didn't work, anyways.
balance: You can't mindswap into PAIs and brains(?).
admin: Admins can now add spells by name or typepath.
admin: Spell requirements are bitflags now, so you can modify them with the bit-field VV ui. Pretty neat.
code: proc_holders have been removed from existence.
refactor: Wizard, Heretic, Revenant, and Genetics spells are now all action datums.
refactor: Xenomorph, Spider, and Cytology monster abilities are now all action datums.
refactor: Some malf AI and cult abilities are now fully action datums instead of an unholy mix of proc holder and action.
refactor: Refactored how cult's blood target is set.
refactor: Bloodcrawling and jaunting have been completely refactored. Blood crawling has been exorcised from the living level of mobs, and the consumption part of (s)laughter demons is now handled by the action itself.
refactor: The wizard's teleport scroll now actually holds and casts a version of the "teleport" spell, instead of fake casting it.
refactor: Refactored the wizard spellbook a bit.
refactor: Refactored how all item actions are applied and handled.
del: SDQL spells have been removed.
fix: The alt click tab (obj tab?) will no longer cause massive clientside lag (unless you alt click that 2000 obj large tofu pile)
fix: The alt click menu is snappier now, try usin it and let me know if anything blows up yeah?
/:cl:

2022-11-18 23:46 UTC, Spyroshark commented
>balance: All wizard spells except Mindswap can't be cast if the wizard is just a brain.

mmis shooting fireballs is a feature

2022-11-20 21:19 UTC, Kapu1178 commented
![image](https://user-images.githubusercontent.com/75460809/202926729-3c4ee5ab-68e1-4c10-b803-975cf5f57294.png)
![image](https://user-images.githubusercontent.com/75460809/202926740-505d4b86-037d-4eab-aadc-d700467b9180.png)
Second may or may not be related. Unsure.

2022-11-20 21:34 UTC, Kapu1178 requested changes

2022-11-20 21:34 UTC, Kapu1178 commented on code/controllers/subsystem/statpanel.dm
> +		global_data = list(
put all my stat panel changes back.

2022-11-21 00:45 UTC, DeadLineSS13 commented on code/controllers/subsystem/statpanel.dm
> +		global_data = list(
> put all my stat panel changes back.

Ready

2022-11-21 00:46 UTC, DeadLineSS13 commented
> ![image](https://user-images.githubusercontent.com/75460809/202926729-3c4ee5ab-68e1-4c10-b803-975cf5f57294.png) ![image](https://user-images.githubusercontent.com/75460809/202926740-505d4b86-037d-4eab-aadc-d700467b9180.png) Second may or may not be related. Unsure.

Fixed first issue. Second issue  mb maded from first issue.

2022-11-27 23:48 UTC, Kapu1178 commented
![image](https://user-images.githubusercontent.com/75460809/204166256-9b0cfa80-00f7-4219-94d5-81a38e8c1a83.png)
![image](https://user-images.githubusercontent.com/75460809/204166269-f4ac49a3-b9ab-4554-add3-19a46a1f1525.png)
^ Duplicate spells. **Also:** Spell icons spawn ontop of eachother frequently.

**Unsure if this is repo or PR issue:** Cult stun duration is almost non existant

2023-02-01 04:39 UTC, Kapu1178 commented
yolo

2023-02-01 04:39 UTC, merged