Adds bay engraving
DaedalusDock/daedalusdock pull request #919
Opened 2024-04-27 18:36 UTC by ToasterBan

## About The Pull Request
As the title says, adds bay-style engraving

use any sharp object on a turf to engrave a message on it
use any sharp object on another engraving to stack engravings ontop of eachother
use a welder to get rid of engravings

<details><summary>Videos</summary>
<p>

https://github.com/DaedalusDock/daedalusdock/assets/54711687/eca103b5-1fef-4f20-afe3-63382176b66b

https://github.com/DaedalusDock/daedalusdock/assets/54711687/e7fa6a79-2592-41df-a02f-befe96a85347

![image](https://github.com/DaedalusDock/daedalusdock/assets/54711687/ebda3338-8d2e-479e-a621-c8be7676ced2)

</p>
</details> 

## Why It's Good For The Game
fun little thing, mechnically its just a smaller spraycan

## Changelog

:cl:
add: Added bay-style engraving, a wall or floor can be engraved with any sharp object
/:cl:

2024-04-27 20:14 UTC, Kapu1178 requested changes

2024-04-27 20:14 UTC, Kapu1178 commented on code/game/turfs/turf.dm
> +	if(!do_after(vandal, src, max(20, length(message))))
```suggestion
	if(!do_after(vandal, src, max(2 SECONDS, length(message), DO_PUBLIC, display = tool)))
```

2024-04-27 20:14 UTC, Kapu1178 commented on code/game/turfs/turf.dm
> +		to_chat(vandal, span_danger("You feel much safer."))
Should probably remove, as this reference does not make sense in daedalus.

2024-04-27 20:14 UTC, Kapu1178 commented on code/game/turfs/turf.dm
> +	. = ..()
```suggestion
/turf/attackby_secondary(obj/item/weapon, mob/user, params)
	. = ..()
	if(. == SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN)
		return

	if(weapon.sharpness && try_graffiti(user, weapon))
		return SECONDARY_ATTACK_CANCEL_ATTACK_CHAIN
```

2024-04-27 21:06 UTC, Kapu1178 requested changes
Looks good other than the pending additions.

2024-04-28 04:38 UTC, Kapu1178 requested changes
There are still two pending reviews, basically just adding checks before and after the inputs/do_after, so that if you, say, get knocked out during the do_after, it will fail.

2024-04-28 09:48 UTC, ToasterBan commented
done, should I run the message trough the IC chat filter before running the do_after or should it be fine?

2024-04-28 16:24 UTC, Kapu1178 requested changes
Don't bother pushing it through the IC filter, we don't even use it anyway, IIRC?

2024-04-28 16:24 UTC, Kapu1178 commented on code/game/turfs/turf.dm
> +		return FALSE
```suggestion
		return TRUE
```
Since we've started an action, even if it's interrupted, it should cancel propagation.

2024-04-28 16:24 UTC, Kapu1178 commented on code/game/turfs/turf.dm
> +		return FALSE
```suggestion
		return TRUE
```

2024-04-28 16:24 UTC, Kapu1178 commented on code/game/turfs/turf.dm
> +		return FALSE
```suggestion
		return TRUE
```

2024-04-28 19:59 UTC, francinum commented
We don't, but for consistency they probably should be hooked in, or we can just rip the entire thing out.

2024-04-28 21:19 UTC, Kapu1178 approved these changes

2024-04-28 23:31 UTC, francinum approved these changes

2024-04-28 23:32 UTC, merged